
#ayaka-plugin 抽象配置属性集合

#todo 人物、武器 的 升级、进阶 UI
#todo 装备武器和圣遗物
#todo 属性面板

strength:
  max: 160       #体力上限
  recovery: 180  #每日体力恢复

syw:
  bag: 8         #圣遗物可保存包裹大小
  essence: 16    #圣遗物精粹(重置圣遗物)获取中位数, 25%上下浮动
  random4: .25   #圣遗物出4词条概率
  strength: 20   #抽取圣遗物消耗体力
  resetCost: 100 #重置圣遗物等级消耗(圣遗物精粹)
  resetLoss: .5  #重置圣遗物概率损成3词条
  levelup:       #圣遗物升级对应消耗(圣遗物精粹) - 废弃
    4: 16
    8: 28
    12: 43
    16: 66
    20: 117

exp:
  strength: 20   #刷经验花消耗体力 - 未处理
  once: 100000   #一次获取经验数量, 上下4w浮动, 保留到千位 -未处理
  double: 4      #考虑周四双倍产出

mora:
  strength: 20   #刷摩拉花消耗体力(突破角色/武器/天赋) - 未处理
  once: 60000    #一次获取摩拉数量 - 未处理
  double: 5      #考虑周五双倍产出

explore:
  strength: 40  #探索消耗体力
  expGain:      #探索每个等级的事件获取的经验数量
    - 1
    - 2
    - 3
    - 4
    - 5
    - 8
    - 10
    - 12
  exp:           #探索升级需要经验
    - 100
    - 200
    - 400
    - 800
    - 1600
    - 3200
    - 4800
    - 6400
    - 8000
    - 12000
