法器:
  - 鹿野院平藏
  - 八重神子
  - 珊瑚宫心海
  - 莫娜
  - 可莉
  - 凝光
  - 丽莎
  - 芭芭拉
  - 砂糖
  - 烟绯

枪:
  - 云堇
  - 申鹤
  - 托马
  - 胡桃
  - 雷电将军
  - 魈
  - 钟离
  - 罗莎莉亚
  - 香菱
  - 赛诺
  - 坎蒂丝

弓:
  - 提纳里
  - 柯莱
  - 夜兰
  - 五郎
  - 达达利亚
  - 埃洛伊
  - 宵宫
  - 温迪
  - 甘雨
  - 九条裟罗
  - 菲谢尔
  - 迪奥娜
  - 安柏

大剑:
  - 多莉
  - 荒泷一斗
  - 优菈
  - 迪卢克
  - 早柚
  - 重云
  - 雷泽
  - 北斗
  - 诺艾尔
  - 辛焱

单手剑:
  - 久岐忍
  - 旅行者（空）
  - 旅行者（荧）
  - 神里绫人
  - 阿贝多
  - 神里绫华
  - 枫原万叶
  - 刻晴
  - 琴
  - 七七
  - 班尼特
  - 行秋
  - 凯亚
  - 莱依拉